# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpcService.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11grpcService.proto\"\x1c\n\x0cPriceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\",\n\rPriceResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x05\x32<\n\rsalesExchange\x12+\n\x08GetPrice\x12\r.PriceRequest\x1a\x0e.PriceResponse\"\x00\x62\x06proto3')
)




_PRICEREQUEST = _descriptor.Descriptor(
  name='PriceRequest',
  full_name='PriceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PriceRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=49,
)


_PRICERESPONSE = _descriptor.Descriptor(
  name='PriceResponse',
  full_name='PriceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PriceResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='PriceResponse.price', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['PriceRequest'] = _PRICEREQUEST
DESCRIPTOR.message_types_by_name['PriceResponse'] = _PRICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PriceRequest = _reflection.GeneratedProtocolMessageType('PriceRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRICEREQUEST,
  '__module__' : 'grpcService_pb2'
  # @@protoc_insertion_point(class_scope:PriceRequest)
  })
_sym_db.RegisterMessage(PriceRequest)

PriceResponse = _reflection.GeneratedProtocolMessageType('PriceResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRICERESPONSE,
  '__module__' : 'grpcService_pb2'
  # @@protoc_insertion_point(class_scope:PriceResponse)
  })
_sym_db.RegisterMessage(PriceResponse)



_SALESEXCHANGE = _descriptor.ServiceDescriptor(
  name='salesExchange',
  full_name='salesExchange',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=97,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPrice',
    full_name='salesExchange.GetPrice',
    index=0,
    containing_service=None,
    input_type=_PRICEREQUEST,
    output_type=_PRICERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SALESEXCHANGE)

DESCRIPTOR.services_by_name['salesExchange'] = _SALESEXCHANGE

# @@protoc_insertion_point(module_scope)
